// Code generated by go:generate; DO NOT EDIT.

package math

import (
	"math"
)
// Core variables: re-exported from the standard math package.
var (
)
var _ = math.Pi // dummy usage to avoid unused import error.
