// Code generated by go:generate; DO NOT EDIT.

package math

import (
	"math"
)
// Core types: re-exported from the standard math package.

var _ = math.Pi // dummy usage to avoid unused import error.
